name: deploy-pile

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger infrastructure deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRASTRUCTURE_PAT }}
          repository: markmorcos/infrastructure
          event-type: deploy-pile
          client-payload: |-
            {
              "repository": "markmorcos/pile",
              "token": "${{ secrets.DEPLOYMENT_TOKEN }}",
              "version": "${{ github.sha }}",
              "config_file": "deployment.yaml"
            }
